# Generated by Django 4.0.4 on 2022-04-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Auction',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='auction',
        ),
    ]
