# Generated by Django 4.0.4 on 2022-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_listing_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
