# Generated by Django 4.0.4 on 2022-04-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_image_auction_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
