# Generated by Django 4.0.4 on 2022-04-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
