# Generated by Django 4.0.4 on 2022-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(default=None, related_name='watchlist', to='auctions.auction'),
        ),
    ]
